spring:
  application:
    name: auth-service
  profiles:
    active: dev

# Logging Configuration
logging:
  file:
    path: logs
    name: ${logging.file.path}/${spring.application.name}.log
  pattern:
    console: "%d{ISO8601} | %highlight(%-5level) | [%thread] | %cyan(%logger{36}) | %msg%n"
    file: "%d{ISO8601} | %-5level | [%thread] | %logger{36} | %msg%n"
  level:
    root: INFO
    com.eande.store.auth_service: DEBUG

# Server configuration
server:
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method